import glob
import json
import logging
import os
from datetime import UTC, datetime

from aitrack.collectors.base import BaseCollector
from aitrack.config import (
    AITRACK_LOG_DIR,
    DEFAULT_DB_PATH,
    KIRO_DB_PATH,
    OPENCODE_DB_PATH,
    OPENCODE_LOG_DIR,
    SEARCH_PATTERNS,
    _parse_log_kv_pairs,
)
from aitrack.models.discovery import DiscoveredSource
from aitrack.models.usage_record import UsageRecord
from aitrack.utils.pricing import calculate_cost

logger = logging.getLogger(__name__)

# Paths already handled by dedicated collectors (OpencodeCollector, KiroCollector)
# or generated by aitrack itself. Skip these to avoid duplicate/irrelevant imports.
_EXCLUDED_PATHS = {DEFAULT_DB_PATH, OPENCODE_DB_PATH, KIRO_DB_PATH}
_EXCLUDED_DIRS = {OPENCODE_LOG_DIR, AITRACK_LOG_DIR}


class GenericCollector(BaseCollector):
    tool_name = "generic"

    def discover(self) -> list[DiscoveredSource]:
        sources = []
        seen = set()
        for pattern in SEARCH_PATTERNS:
            for path in glob.glob(pattern):
                if path in seen:
                    continue
                seen.add(path)
                if not os.path.isfile(path):
                    continue
                if path in _EXCLUDED_PATHS or os.path.dirname(path) in _EXCLUDED_DIRS:
                    continue
                name = os.path.basename(path)
                ext = name.split(".")[-1] if "." in name else ""
                compatible = ext in ("json", "ndjson", "log", "csv")
                sources.append(
                    DiscoveredSource(
                        tool_name="generic",
                        source_type=f"file_{ext}" if ext else "file_unknown",
                        path=path,
                        parser_compatible=compatible,
                    )
                )
        return sources

    def collect(self, source: DiscoveredSource) -> list[UsageRecord]:
        records = []
        content = None
        try:
            with open(source.path) as f:
                content = f.read()
        except Exception as e:
            logger.warning("cannot read %s: %s", source.path, e)
            return records

        if content is None:
            return records

        if source.path.endswith(".ndjson"):
            records = self._parse_ndjson(content, source.path)
        elif source.path.endswith(".json"):
            records = self._parse_json(content, source.path)
        elif source.path.endswith(".log"):
            records = self._parse_log(content, source.path)

        return records

    def _parse_json(self, content: str, source_path: str) -> list[UsageRecord]:
        records = []
        try:
            data = json.loads(content)
        except json.JSONDecodeError:
            return records

        if isinstance(data, list):
            for item in data:
                record = self._extract_from_dict(item, source_path)
                if record:
                    records.append(record)
        elif isinstance(data, dict):
            if "usage" in data or "records" in data:
                items = data.get("usage", data.get("records", []))
                if isinstance(items, list):
                    for item in items:
                        record = self._extract_from_dict(item, source_path)
                        if record:
                            records.append(record)
            else:
                record = self._extract_from_dict(data, source_path)
                if record:
                    records.append(record)
        return records

    def _parse_ndjson(self, content: str, source_path: str) -> list[UsageRecord]:
        records = []
        for line in content.strip().split("\n"):
            if not line.strip():
                continue
            try:
                item = json.loads(line)
                record = self._extract_from_dict(item, source_path)
                if record:
                    records.append(record)
            except json.JSONDecodeError:
                continue
        return records

    def _parse_log(self, content: str, source_path: str) -> list[UsageRecord]:
        records = []
        for line in content.strip().split("\n"):
            if "token" not in line.lower() and "usage" not in line.lower():
                continue
            parts = _parse_log_kv_pairs(line)
            if "tokens.input" in parts or "total_tokens" in parts:
                try:
                    ts = parts.get("timestamp", "")
                    timestamp = (
                        datetime.fromisoformat(ts.replace("Z", "+00:00"))
                        if ts
                        else datetime.now(UTC)
                    )
                    record = UsageRecord(
                        timestamp=timestamp,
                        tool_name="generic",
                        provider=parts.get("provider", parts.get("model.providerID", "unknown")),
                        model=parts.get("model", parts.get("model.id", "unknown")),
                        input_tokens=int(parts.get("tokens.input", parts.get("input_tokens", 0))),
                        output_tokens=int(
                            parts.get("tokens.output", parts.get("output_tokens", 0))
                        ),
                        session_id=parts.get("session_id", parts.get("id", "")),
                        source_file=source_path,
                    )
                    record.estimated_cost = calculate_cost(
                        provider=record.provider,
                        model=record.model,
                        input_tokens=record.input_tokens,
                        output_tokens=record.output_tokens,
                    )
                    records.append(record)
                except Exception:
                    continue
        return records

    def _extract_from_dict(self, item: dict, source_path: str) -> UsageRecord | None:
        try:
            tool_name = str(item.get("tool", item.get("tool_name", "generic")))
            provider = str(item.get("provider", "unknown"))
            model = str(item.get("model", "unknown"))
            input_tokens = int(item.get("input_tokens", item.get("prompt_tokens", 0)))
            output_tokens = int(item.get("output_tokens", item.get("completion_tokens", 0)))
            total_tokens = int(item.get("total_tokens", input_tokens + output_tokens))

            ts_raw = item.get("timestamp", item.get("created_at", item.get("time", "")))
            timestamp = datetime.now(UTC)
            if isinstance(ts_raw, (int, float)):
                timestamp = datetime.fromtimestamp(
                    ts_raw / 1000 if ts_raw > 1e12 else ts_raw, tz=UTC
                )
            elif isinstance(ts_raw, str):
                try:
                    timestamp = datetime.fromisoformat(ts_raw.replace("Z", "+00:00"))
                except ValueError:
                    pass

            session_id = str(
                item.get("session_id", item.get("conversation_id", item.get("id", "")))
            )
            cost_val = float(item.get("cost", item.get("estimated_cost", 0)))

            estimated_cost = calculate_cost(
                provider=provider,
                model=model,
                input_tokens=input_tokens,
                output_tokens=output_tokens,
            )
            if cost_val > 0:
                estimated_cost = cost_val

            return UsageRecord(
                timestamp=timestamp,
                tool_name=tool_name,
                provider=provider,
                model=model,
                input_tokens=input_tokens,
                output_tokens=output_tokens,
                total_tokens=total_tokens,
                estimated_cost=estimated_cost,
                session_id=session_id,
                source_file=source_path,
            )
        except Exception as e:
            logger.debug("generic parse error: %s", e)
            return None
